apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: node-namespace
spec:
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: guimassoqueto/node-api:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.5"
          limits:
            memory: "512Mi"
            cpu: "1"
        envFrom:
          - secretRef:
              name: node-secret
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 20
        securityContext:
          runAsUser: 1000