version: '3.9'

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DB_NAME}"
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - local
    restart: always
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok' | mongosh 0.0.0.0:${MONGO_PORT}/ --quiet"
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 30s

  node-api:
    container_name: node-api
    build:
      context: .
      dockerfile: Dockerfile
    image: node-api
    env_file:
      - .env
    environment:
      MONGO_HOST: "mongodb"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - local
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "0.0.0.0:${APP_PORT}/healthcheck"]
      interval: 5s
      timeout: 2s
      retries: 3
    expose:
      - ${APP_PORT}
    entrypoint:
      - node
    command: 
      - dist/main/main.js

networks:
  local:
    name: local
    driver: bridge
