version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_ROOT_USERNAME=username
      - MONGO_ROOT_PASSWORD=password
      - MONGO_DB_NAME=clean-node-api
      - MONGO_PORT=27017
    ports: 
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - local
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok' | mongosh 0.0.0.0:${MONGO_PORT}/ --quiet"
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 30s
      
networks:
  local:
    name: local
    driver: bridge