version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DB_NAME}"
    ports:
      - 27017:27017
    networks:
      - local
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok' | mongosh 0.0.0.0:27017/ --quiet"
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 30s
      
networks:
  local:
    name: local
    driver: bridge