apiVersion: v1
kind: Namespace
metadata:
  name: node-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-configmap
  namespace: node-namespace
data:
  MONGO_URL: "<paste-MONGO_URL-here>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: node-namespace
spec:
  selector:
    matchLabels:
      app: node-api
  replicas: 1
  template:
    metadata:
      name: node-api-pod
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: guimassoqueto/node-api:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: node-configmap
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: node-namespace
spec:
  type: NodePort
  selector:
    app: node-api
  ports:
  - port: 8000
    targetPort: 8000