name: Node.js CI

env:
  MONGO_DB_NAME: ${{ vars.MONGO_DB_NAME }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]
        mongodb-version: ['latest']


    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}  
          mongodb-username: 'user'
          mongodb-password: 'pwd'
          mongodb-db: 'node-clean-api' 
      
      - name: Run Unit Tests
        run: npm install && npm run test:unit
        
      - name: Run Integration Tests
        run: npm install && test:integration
        env:
          MONGO_ROOT_USERNAME: ${{ vars.MONGO_ROOT_USERNAME }}
          MONGO_ROOT_PASSWORD: ${{ vars.MONGO_ROOT_PASSWORD }}
          MONGO_HOST: ${{ vars.MONGO_HOST }}
          MONGO_PORT: ${{ vars.MONGO_PORT }}
          MONGO_DB_NAME: ${{ vars.MONGO_DB_NAME }}
          MONGO_URL: ${{ vars.MONGO_URL }}